// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aplicacaoalmirtrabalho.Models;

namespace aplicacaoalmirtrabalho.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.jogos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("empresaID")
                        .HasColumnType("int");

                    b.Property<double>("preco")
                        .HasColumnType("float");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("empresaID");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("idade")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cffc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("jogosID")
                        .HasColumnType("int");

                    b.Property<double>("precototal")
                        .HasColumnType("float");

                    b.Property<int>("usuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("jogosID");

                    b.HasIndex("usuarioID");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.jogos", b =>
                {
                    b.HasOne("aplicacaoalmirtrabalho.Models.Dominio.empresa", "empresas")
                        .WithMany("jogos")
                        .HasForeignKey("empresaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("empresas");
                });

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.venda", b =>
                {
                    b.HasOne("aplicacaoalmirtrabalho.Models.Dominio.jogos", "jogo")
                        .WithMany("venda")
                        .HasForeignKey("jogosID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("aplicacaoalmirtrabalho.Models.Dominio.usuario", "usuarios")
                        .WithMany("venda")
                        .HasForeignKey("usuarioID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("jogo");

                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.empresa", b =>
                {
                    b.Navigation("jogos");
                });

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.jogos", b =>
                {
                    b.Navigation("venda");
                });

            modelBuilder.Entity("aplicacaoalmirtrabalho.Models.Dominio.usuario", b =>
                {
                    b.Navigation("venda");
                });
#pragma warning restore 612, 618
        }
    }
}
